dist: xenial
language: python
jobs:
  include:
  - python: '3.7'
  - python: '2.7'
install:
- pip install -r requirements_dev.txt
- pip install -e .
script:
- flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
- flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
- pytest --cov-report term-missing --cov=pychromatic tests/
deploy:
  provider: pypi
  user: srmnitc
  password:
    secure: AjQ8Qcznsh07ObQ6IImJ9UGMAeZaQd00sHvHKGpx8Ru+Y3z/F93ZrEIe8dzHcJIgBUsb0DyBEEEMnA1p9sCnITA3P2MoyE0Jtm1mmdGMnC1w5VVwMjJUrG96vWbkmy32rXz7k2BiMhwGxbOKE8wyyEWc3Vau2DG8Xeb01f3a1tK6zXXDdv+tbMqhbjE1ev9s6rnKL3T6GvRNChAnwJpXAr1CP75nNPbsp10HXPMQzeGXwkQXmtbd/iAhzv8ub7oqsgB1jqmLjDFcRqtUMd1pTTAX6Pgc6iAk8FohPp+kTacTVxO+/bszMjoqOC4zIH0kh8CjjNbb24gJvGDGSTNFmgwzdE/NZM9m4NPuU1yf/RuVAPqJGYI7pEYirWw6QvcaCZ2nvyeFCE7LxeTOPxUvLnKbG1Sbb2ghCNz69mGUTnPx7sxY2R2MLyc/aNWDG85guKf6q1/F3N5lqM8YBAHzR/XTGbM9x8FdmntymbYe9XObRCGKYSJRlO6fzTX1DmDDNLoF34QuCwbWXQRLrr4L67XCq0c+T/TYb6m6+jPeFT0VCLaCWFkpMHwArmlAa7AWPmmdgTTVHAUxPwJljjh8u1sMVqhEqAx7jf4NdYVrwE6Jh4hE4eWRnubPuwsT5SHq4M5e5xTGVBKVVQA5U8wR7w7P2Snze1XrDSM28j9petY=
