dist: xenial
language: python
jobs:
  include:
    - python: "3.7"
    - python: "2.7"
install:
  - pip install -r requirements_dev.txt
  - pip install -e .
script:
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  - pytest --cov-report term-missing --cov=pychromatic tests/
